<?php

class pocketlistsListDetailsAction extends waViewAction
{
    public function execute()
    {
        $id = waRequest::post('id', false, waRequest::TYPE_INT);
        $im = new pocketlistsListModel();
        if ($id) {
            $list = $im->getById($id);
            $user_name  = new waContact($list['contact_id']);
            $list['username'] = $user_name->getName();
            $this->view->assign('list', $list);

            // get icons
            $this->view->assign('list_icons', $this->getIcons());
        }
    }

    private function getIcons()
    {
//        $path = wa()->getAppPath('img/listicons/', wa()->getApp());
        $icons = array(
            "list",
            "achtung",
            "books",
            "calendar",
            "construction",
            "gift",
            "grocery",
            "gym",
            "idea",
            "invoice",
            "medicine",
            "money",
            "passport",
            "recipe",
            "star",
            "travel",
            "vacations",

            "award",
            "bag",
            "calcuator",
            "cart",
            "checkout",
            "clock",
            "coins",
            "contact",
            "delivery",
            "diagram",
            "home",
            "list2",
            "lock",
            "palette",
            "pencil",
            "phone",
            "piggy",
            "plane",
            "service",
            "tools",
            "video",
            "work",
            "calendar-notavailable",

            "paid-christmas",
            "paid2-christmas-ball",
            "paid2-christmas-stocking",
            "paid2-santa",
            "paid2-snowman",
            "paid2-gingerbread",
            "paid2-mistletoe",
            "paid-birthday",
            "paid-baloons",

            "paid-map",
            "paid2-location",
            "paid-music",
            "paid-microphone",
            "paid-newspaper",
            "paid-notepad",
            "paid-tie",
            "paid2-car",
            "paid2-chat",
            "paid2-clock",
            "paid2-iphone",
            "paid2-keys",
            "paid2-sunglasses",
            "paid2-yinyang",
            "paid2-camera",
            "paid2-hotspot",
            "paid2-ladies-shoe",
            "paid2-checkmark",
            "paid2-landscape",
            "paid2-guitar",
            "paid2-tent",
            "paid2-crab",
            "paid2-boxes",
            "paid2-arrows",
            "paid-run",
            "paid-bicycle",
            "paid-baseball",
            "paid-basketball",
            "paid-football",

            "paid-avocado",
            "paid-banana",
            "paid-apple",
            "paid-pear",
            "paid-corn",
            "paid-watermelon",
            "paid-carrot",
            "paid-pizza",
            "paid-steak",
            "paid-icecream",
            "paid-lollipops",
            "paid-spaghetti",
            "paid-chicken",
            "paid-eggs",
            "paid-bread",
            "paid-candy",
            "paid-cherry",
            "paid-coffee",
            "paid-starbucks",
            "paid-cocktail",
            "paid-whisky-bottle",
            "paid-wine-bottle",
            "paid-wine-glass",

            "paid-rain",
            "paid-cloud-sun",
            "paid-sun",
            "paid-snow",
            "paid-thunderstorm",
            "paid-umbrella",
            "paid-alarmclock",

            "paid-baby",
            "paid-babybottle",
            "paid-bear",
            "paid-dogcat",
            "paid-animal",
            "paid-armchair",
            "paid-bed",
            "paid-chestofdraws",
            "paid-desk",
            "paid-diamond",
            "paid-discount",
            "paid-dj",
            "paid-diskette",
            "paid-education",
            "paid-fire-ext",
            "paid-flashlight",
            "paid-flower",
            "paid-gameboy",
            "paid-gamecontroller",
            "paid-globe",
            "paid-saturn",
            "paid-ufo",
            "paid-alien",
            "paid-hammer",
            "paid-hanger",
            "paid-wardrobe",
            "paid-tv",
            "paid-imac",
            "paid-safebox",
            "paid-scissors",
            "paid-sock",
            "paid-paint",
            "paid-paintbrush",
            "paid-klmn",
            "paid-knives",
            "paid-pan",
            "paid-pin",
            "paid-scoop",
            "paid-thermo",
            "paid-trash",

            "yeme-beer",
            "yeme-becherovka",
            "yeme-mojito",
            "yeme-cognac",
            "yeme-redwine",
            "yeme-blue-hawaii",
            "yeme-whisky",
            "yeme-jagermeister",

            "flag-eu",
            "flag-usa",
            "flag-canada",
            "flag-uk",
            "flag-australia",
            "flag-new-zealand",
            "flag-france",
            "flag-germany",
            "flag-italy",
            "flag-spain",
            "flag-portugal",
            "flag-switzerland",
            "flag-netherlands",
            "flag-norway",
            "flag-sweden",
            "flag-finland",
            "flag-denmark",
            "flag-belgium",
            "flag-greece",
            "flag-japan",
            "flag-china",
            "flag-hongkong",
            "flag-korea",
            "flag-india",
            "flag-russia",
            "flag-ukraine",
            "flag-belarus",
            "flag-israel",
            "flag-turkey",
            "flag-brazil",
            "flag-jamaica",
            "flag-argentina",
            "flag-chile",
            "flag-colombia",
            "flag-vietnam",
            "flag-thailand",
            "flag-mexico",
            "flag-south-africa",
            "flag-indonesia",
            "flag-kenya",

            "paid3-smiley-happy",
            "paid3-smiley-unhappy",
            "paid3-bookmark",
            "paid3-ribbon",
            "paid3-apple",
            "paid3-anchor",
            "paid3-trafficlight",
            "paid3-goal",
            "paid3-userpic-hipster",
            "paid3-userpic-man",
            "paid3-userpic-lady",
            "paid3-userpic-steve",

            "paid4-christmas-reindeer",
            "paid4-christmas-sleigh",
            "paid4-christmas-gloves",
            "paid4-christmas-santa",
            "paid4-christmas-house",
            "paid4-christmas-tree",
            "paid4-christmas-cocktail",
            "paid4-christmas-glass",
            "paid4-christmas-giftbox",
            "paid4-christmas-giftbox2",
            "paid4-christmas-calendar",
            "paid4-christmas-candy",
            "paid4-christmas-gingerbread",
            "paid4-christmas-snowman",
            "paid4-christmas-sale",
            "paid4-christmas-globes",
        );
        foreach ($icons as $icon_id => $icon) {
            $icons[$icon_id] = 'li-'.$icon.'@2x.png';
        }

        return $icons;
    }
}