# validate https://editor.swagger.io/
openapi: 3.0.0
info:
  title: 'Pocket Lists API'
  description: ''
  version: 1.0.0
servers:
  - url: /api.php
    description: Current host server

paths:
#  /pocketlists.item.add:
#  /pocketlists.item.delete:
#  /pocketlists.item.get:
#  /pocketlists.item.update:
  /pocketlists.list.add:
    put:
      security:
        - BearerAuth: [ ]
      summary: Добавить новый список
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - pocket_id
              properties:
                name:
                  type: string
                  description: Название списка
                type:
                  type: string
                  default: checklist
                  description: |
                    Тип списка
                    + checklist - перечень дел
                    + notes - заметки
                  enum:
                    - checklist
                    - notes
                pocket_id:
                  type: string
                  description: ID проекта
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list_id:
                    type: integer
                    description: ID списка
                  item_id:
                    type: integer
                    description: ID элемента
        400:
          description: Invalid request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        403:
          description: Access denied to the Pocket Lists app or this API method.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        404:
          description: Pocket not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        405:
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        500:
          description: Internal server error.
#  /pocketlists.list.delete:
  /pocketlists.list.get:
    get:
      security:
        - BearerAuth: [ ]
      summary: Получить список
      parameters:
        - in: query
          name: id
          description: ID списка
          schema:
            type: integer
        - in: query
          name: starting_from
          description: Временная метка, начиная с которой возвращаются записи
          schema:
            type: integer
        - in: query
          name: limit
          description: Размер порции списка (по умолчанию 30, максимум 500)
          schema:
            type: integer
        - in: query
          name: offset
          description: Смещение списка (по умолчанию 0)
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: List identifier
                    name:
                      type: string
                      description: Name list
                    contact_id:
                      type: integer
                      description: Contact identifier
                    pocket_id:
                      type: integer
                      description: Pocket identifier
                    type:
                      type: string
                      description: List type
                    icon:
                      type: string
                      description: Icon
                    color:
                      type: string
                      description: Color
                    sort:
                      type: integer
                      description: Sort
                    create_datetime:
                      type: string
                      format: date-time
                      description: Create datetime
                    update_datetime:
                      type: string
                      format: date-time
                      description: Update datetime
        400:
          description: Invalid request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        403:
          description: Access denied to the Pocket Lists app or this API method.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        404:
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        405:
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        500:
          description: Internal server error.
#  /pocketlists.list.update:

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    errorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error code
        error_description:
          type: string
          description: Error description
