<?php
return array(
    'pocketlists_attachment' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'item_id' => array('int', 11, 'null' => 0),
        'filename' => array('text'),
        'size' => array('int', 11, 'null' => 0),
        'ext' => array('varchar', 10, 'null' => 0),
        'storage' => array('enum', "'public', 'protected'", 'default' => 'protected'),
        'upload_datetime' => array('datetime'),
        'uuid' => array('varchar', 36),
        ':keys' => array(
            'PRIMARY' => 'id',
            'item_id' => 'item_id',
        ),
    ),
    'pocketlists_comment' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'item_id' => array('int', 11),
        'contact_id' => array('int', 11),
        'comment' => array('text'),
        'create_datetime' => array('datetime'),
        'update_datetime' => array('datetime'),
        'client_touch_datetime' => array('datetime'),
        'uuid' => array('varchar', 36),
        ':keys' => array(
            'PRIMARY' => 'id',
            'item_id' => 'item_id',
            'contact_id' => 'contact_id',
        ),
    ),
    'pocketlists_item' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'list_id' => array('int', 11),
        'contact_id' => array('int', 11),
        'parent_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'rank' => array('varchar', 16, 'null' => 0, 'default' => ''),
        'has_children' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'priority' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'calc_priority' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'create_datetime' => array('datetime'),
        'update_datetime' => array('datetime'),
        'activity_datetime' => array('datetime'),
        'complete_datetime' => array('datetime'),
        'complete_contact_id' => array('int', 11),
        'name' => array('mediumtext'),
        'note' => array('text'),
        'due_date' => array('date'),
        'due_datetime' => array('datetime'),
        'client_touch_datetime' => array('datetime'),
        'location_id' => array('int', 11),
        'amount' => array('decimal', "10,0"),
        'currency_iso3' => array('varchar', 3),
        'assigned_contact_id' => array('int', 11),
        'repeat_frequency' => array('int', 11, 'null' => 0, 'default' => '0'),
        'repeat_interval' => array('varchar', 20),
        'repeat_occurrence' => array('int', 11),
        'key_list_id' => array('int', 11),
        'uuid' => array('varchar', 36),
        'pro_label_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'parent' => 'parent_id',
            'list_id' => 'list_id',
            'sort' => array('parent_id', 'sort', 'rank'),
            'key_list_id' => 'key_list_id',
            'complete_contact_id' => 'complete_contact_id',
            'contact_id' => 'contact_id',
            'assigned_contact_id' => 'assigned_contact_id',
        ),
    ),
    'pocketlists_item_link' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'item_id' => array('int', 11, 'null' => 0),
        'app' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'entity_type' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'entity_id' => array('varchar', 36, 'null' => 0),
        'data' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'item_id_2' => array('item_id', 'app', 'entity_type', 'entity_id', 'unique' => 1),
            'item_id' => 'item_id',
        ),
    ),
    'pocketlists_item_move' => array(
        'item_id' => array('int', 11, 'null' => 0),
        'prev_list_id' => array('int', 11,),
        'prev_pocket_id' => array('int', 11),
        'prev_status' => array('tinyint', 1),
        'datetime' => array('datetime')
    ),
    'pocketlists_item_tags' => array(
        'item_id' => array('int', 11, 'null' => 0),
        'tag_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('item_id', 'tag_id'),
        ),
    ),
    'pocketlists_list' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'pocket_id' => array('int', 11),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'rank' => array('varchar', 16, 'null' => 0, 'default' => ''),
        'type' => array('enum', "'checklist','notes'"),
        'icon' => array('varchar', 64),
        'private' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'archived' => array('tinyint', 1, 'default' => '0'),
        'hash' => array('varchar', 32),
        'color' => array('enum', "'none','red','green','blue','yellow','purple'", 'default' => 'none'),
        'passcode' => array('varchar', 32),
        'key_item_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'pocket_id' => 'pocket_id',
            'sort' => array('sort', 'rank')
        ),
    ),
    'pocketlists_location' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'default' => ''),
        'color' => array('varchar', 32, 'default' => ''),
        'location_latitude' => array('decimal', '12,8'),
        'location_longitude' => array('decimal', '12,8'),
        'location_radius' => array('int', 11),
        'create_datetime' => array('datetime'),
        'update_datetime' => array('datetime'),
        'activity_datetime' => array('datetime'),
        'uuid' => array('varchar', 36),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'pocketlists_log' => array(
        'id' => array('bigint', 20, 'null' => 0, 'autoincrement' => 1),
        'action' => array('varchar', 30, 'null' => 0),
        'entity_type' => array('varchar', 30),
        'contact_id' => array('int', 11),
        'pocket_id' => array('int', 11),
        'list_id' => array('int', 11),
        'item_id' => array('int', 11),
        'comment_id' => array('int', 11),
        'attachment_id' => array('int', 11),
        'location_id' => array('int', 11),
        'additional_id' => array('int', 11),
        'assigned_contact_id' => array('int', 11),
        'params' => array('text'),
        'create_datetime' => array('datetime'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'pocketlists_log_action_index' => 'action',
            'pocketlists_log_contact_id_index' => 'contact_id',
            'pocketlists_log_item_id_index' => 'item_id',
            'pocketlists_log_list_id_index_2' => 'list_id',
            'pocketlists_log_pocket_id_index' => 'pocket_id',
        ),
    ),
    'pocketlists_notification' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'type' => array('varchar', 30, 'null' => 0),
        'identifier' => array('varchar', 64),
        'handler' => array('text'),
        'created_at' => array('datetime', 'null' => 0),
        'delayed_to' => array('datetime'),
        'sent_at' => array('datetime'),
        'status' => array('varchar', 255),
        'error' => array('text'),
        'data' => array('text'),
        'contact_id' => array('int', 11),
        'direction' => array('varchar', 10, 'default' => 'external'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'pocketlists_notification_status_index' => 'status',
        ),
    ),
    'pocketlists_pocket' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'rank' => array('varchar', 16, 'null' => 0, 'default' => ''),
        'name' => array('varchar', 200),
        'color' => array('enum', "'none','red','green','blue','yellow','purple'", 'null' => 0, 'default' => 'blue'),
        'create_datetime' => array('datetime'),
        'update_datetime' => array('datetime'),
        'activity_datetime' => array('datetime'),
        'client_touch_datetime' => array('datetime'),
        'passcode' => array('varchar', 32),
        'uuid' => array('varchar', 36),
        ':keys' => array(
            'PRIMARY' => 'id',
            'sort' => array('sort', 'rank')
        ),
    ),
    'pocketlists_pro_automation' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'event' => array('text', 'null' => 0),
        'rules' => array('text', 'null' => 0),
        'action' => array('text', 'null' => 0),
        'type' => array('enum', "'shop'", 'null' => 0),
        'created_by' => array('int', 11, 'null' => 0),
        'created_datetime' => array('datetime'),
        'updated_datetime' => array('datetime'),
        'execution_count' => array('int', 11),
        'last_execution_datetime' => array('datetime'),
        'enabled' => array('tinyint', 3, 'unsigned' => 1, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'pocketlists_pro_delayed_automation' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'automation_id' => array('int', 11, 'null' => 0),
        'status' => array('smallint', 6, 'null' => 0, 'default' => '0'),
        'event_data' => array('text', 'null' => 0),
        'apply_datetime' => array('datetime', 'null' => 0),
        'created_datetime' => array('datetime', 'null' => 0),
        'executed_datetime' => array('datetime'),
        'error' => array('text'),
        'item_id' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'pocketlists_pro_label' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('mediumtext'),
        'color' => array('varchar', 6, 'null' => 0),
        'sort' => array('mediumint', 9),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'pocketlists_pro_shortcut' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 200, 'null' => 0),
        'group' => array('tinyint', 4, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'pocketlists_pro_shortcut_group_name_uindex' => array('group', 'name', 'unique' => 1),
        ),
    ),
    'pocketlists_push_client' => array(
        'client_id' => array('varchar', 255, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'api_token' => array('varchar', 32),
        'create_datetime' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'client_id',
            'pocketlists_push_client_client_id_uindex' => array('client_id', 'unique' => 1),
            'pocketlists_push_client_contact_id_index' => 'contact_id',
        ),
    ),
    'pocketlists_tag' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'text' => array('varchar', 200, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id', 'text'),
        ),
    ),
    'pocketlists_user_favorites' => array(
        'item_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('item_id', 'contact_id'),
        ),
    ),
);
